#!/bin/bash

export XCURSOR_SIZE=12

 if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
   [ -x "$f" ] && . "$f"
  done
  unset f
 fi

xbindkeys -f $HOME/.config/xbindkeysrc

~/src/status/main &

#cool &
setsid gentoo-pipewire-launcher restart &
xwallpaper --daemon --zoom $(activate-linux ~/media/images/wallpapers/DSC0510\ ladder.JPG) &
unclutter --jitter 3 --timeout 2 &
dunst &
hsetroot
fastcompmgr &
#/usr/lib/pentablet/PenTablet.sh \mini &

dwm

