#!/bin/sh

 if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
   [ -x "$f" ] && . "$f"
  done
  unset f
 fi

xbindkeys

~/src/status/main &

#cool &
setsid gentoo-pipewire-launcher restart &
xwallpaper --daemon --zoom ~/media/images/wallpapers/DSC0510\ ladder.JPG &
unclutter &
dunst &
fastcompmgr &
#/usr/lib/pentablet/PenTablet.sh \mini &

dwm

